language: minimal
os: linux
dist: focal
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -qq pandoc texlive-latex-base texlive-latex-recommended lmodern texlive-fonts-recommended texlive-latex-extra
before_script: cd dev
script:
- mkdir -p ./{pdf,html}
- make
- tar -czvf specs.tar.gz html pdf
deploy:
  provider: releases
  name: ${TRAVIS_COMMIT}
  skip_cleanup: true
  file_glob: true
  file:
    - html/*
    - pdf/*
    - specs.tar.gz
  api_key:
    secure: "KFfCA5IRO4W4ElyCagPGVNPgGGexIWsJqyfDh2lrhhsJYfcW0QlGuZbmEZGo2XSu6iQJzxovT/beRjA4Ic1rvp/PQpyYRf7VUSr07JOhm/Va5A+X+WBSHvSFyU1NMkny4B43V0fvfXpOJp7Pp48oZeEo8zt5OJ5OETRsEAdOFyy9mQYn740NTkPPgl8YC6/a/Wjyf0BHNw02ovPRz+jJSUm4Kpr/AAxnSbLnyIQaJxIeSGtGVlxpyZipTzCRNtyXfK6QFFwClINlcVjw2e6AFLINPsnTLEwdsBQB8hdcXm9pEXWTOK90PCOY4bTnrqOYjG3Asai1yUPbjm+45JckVb+is53/VMBSjQoy6YLjjkGFFZ5wE1K7Fww2B/tL4ofoUU9UkkhydALSL476M02QJgGGGi/t92AB2Ofi+ne/vVhdrQdf3whJFVOj9wre8UcFftOqeRkqcIH7dJW8OS6SOug76+jAzqv2/ALVTk6aJaZRquBi8GOqocYnrwakUwV1kOg51n9ZV0vB9+0BQw2N7gcuoQ++J0yIyI8BQ680b1xK4Xu5AAfd9RkG24IPbVB1NWaJ4tOY5nZm8EOoHltxVc4wc6rWkRRwBQrmc+XOv1AoVh6awotyN6gI9Yw9MjHL7SD4MRA6rJFbpV1Ewy4Tpo6Ee9MbHJzWnbFKayeqjS0="
  on:
    repo: algorandfoundation/specs
    branch: master
